version: '3.8'

services:
  web:
    build: .
    container_name: ${APP_CONTAINER_NAME}
    ports:
      - "${APP_PORT}:5001"
    env_file:
      - .env
    volumes:
      - .:/app
      - uploads_data:/app/media/uploads
    networks:
      - app_network
    command: >
      bash -c "
      echo 'Starting Gunicorn...';
      gunicorn -w 4 -b 0.0.0.0:5001 'app.app:create_app()'
      "

volumes:
  uploads_data:

networks:
  app_network:
    driver: bridge
